services:
  draw-docs:
    container_name: draw-docs
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      default:
        ipv4_address: 172.22.0.6

networks:
  default:
    name: nginx_network
    external: true
